[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "arthurdanjou@outlook.fr"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[log]
  filePath = "./traefik.log"

[providers.docker]
  watch = true
  network = "proxy"

[providers.file]
  filename = "traefik_dynamic.toml"

[pilot]
    token = ""
