version: "3"

networks:
  proxy:
    name: proxy
    external: true
  artnetwork:
    name: artnetwork
    external: false

services:
  ares:
    image: ares:latest
    container_name: ares
    restart: unless-stopped
    labels:
      - traefik.http.routers.ares.rule=Host(`arthurdanjou.fr`)
      - traefik.http.routers.ares.tls=true
      - traefik.http.routers.ares.tls.certresolver=lets-encrypt
      - traefik.docker.network=proxy
      - traefik.port=443
    ports:
      - 3333:3333
    networks:
      - artnetwork
      - proxy
    depends_on:
      - athena
    volumes:
      - "/root/artservices/ares/.env:/usr/src/ares/.env:ro"
  resume:
    image: resume:latest
    container_name: resume
    restart: unless-stopped
    labels:
      - traefik.http.routers.resume.rule=Host(`resume.arthurdanjou.fr`)
      - traefik.http.routers.resume.tls=true
      - traefik.http.routers.resume.tls.certresolver=lets-encrypt
      - traefik.docker.network=proxy
      - traefik.port=443
    ports:
      - 3344:3344
    networks:
      - proxy
  athena:
    image: athena:latest
    container_name: athena
    restart: unless-stopped
    labels:
      - traefik.http.routers.athena.rule=Host(`api.arthurdanjou.fr`)
      - traefik.http.routers.athena.tls=true
      - traefik.http.routers.athena.tls.certresolver=lets-encrypt
      - traefik.docker.network=proxy
      - traefik.port=443
    ports:
      - 5555:5555
    networks:
      - artnetwork
      - proxy
    depends_on:
      - mariadb
      - athena_redis
    volumes:
      - "/root/artservices/athena/.env:/usr/src/athena/build/.env:ro"
      - "/root/artservices/athena/storage:/usr/src/athena/build/storage"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - TZ=EUROPE/PARIS
    networks:
      - artnetwork
    ports:
      - 3306:3306
    volumes:
      - "/root/mariadb/data:/var/lib/mysql"
  athena_redis:
    image: redis:latest
    container_name: athena_redis
    restart: unless-stopped
    command: redis-server
    networks:
      - artnetwork
    volumes:
      - "/root/artservices/redis:/data"
